* RSS
** Packetstorm Entries
  :FEEDSTATUS:
(("https://packetstormsecurity.com/news/view/31609/Instagram-Flaw-Shows-Importance-Of-Managing-Third-Party-Apps-Images.html" t "b9634ac01fa3e6ee1feebfc555db317732089e5c")
 ("https://packetstormsecurity.com/news/view/31608/Update-Now-Cisco-Warns-Over-25-High-Impact-Flaws.html" t "b67d80d95e21543cc3ce83d07b7c1e21e5f65df6")
 ("https://packetstormsecurity.com/news/view/31610/Cambridge-Analyticas-Ex-CEO-Banned-From-Running-Companies.html" t "dff0e4cef774e2197fc3ef79a8d4069b873f0007")
 ("https://packetstormsecurity.com/news/view/31611/Alien-Android-Banking-Trojan-Sidesteps-2FA.html" t "4cec3c10f041a551fcb0dece41958aad302e43af")
 ("https://packetstormsecurity.com/news/view/31607/Amazon-Unveils-Flying-Ring-Security-Drone.html" t "354413c2ac0be9f6d200e58b5c49554934f24ff5")
 ("https://packetstormsecurity.com/news/view/31606/Facebook-Shuts-Down-Russians-Posting-As-Journalists.html" t "9a556f200075021ef62a2c592dcdbca06efe6c53")
 ("https://packetstormsecurity.com/news/view/31605/Twitter-Prepares-For-US-Elections-With-Security-Training-Pen-Tests.html" t "d4d30447d873e656c92e4eda0d336ffca128207c")
 ("https://packetstormsecurity.com/news/view/31604/Microsoft-Leaks-6.5TB-In-Bing-Search-Data-Via-Unsecured-Elastic-Server.html" t "cee63599537ec0e10bf738c2ea088cf83c4318da")
 ("https://packetstormsecurity.com/news/view/31603/Leaked-FinCEN-Files-Expose-Poor-Data-Security.html" t "12048e3933876012fe3ae14b7a7f0345bee43cf2")
 ("https://packetstormsecurity.com/news/view/31602/Microsoft-Overhauls-Patch-Tuesday-Security-Update-Guide.html" t "98c429b5f19fdaaa64abeede104e494d5dcdc336")
 ("https://packetstormsecurity.com/news/view/31601/OldGremlin-Ransomware-Group-Bedevils-Russian-Orgs.html" t "276ca59581487b276fde091d92a33482fd1e260d")
 ("https://packetstormsecurity.com/news/view/31600/The-Fight-Over-The-Fight-For-Californias-Privacy-Future.html" t "9444a23efc325257f8663ea3b7cc1cde305e885e")
 ("https://packetstormsecurity.com/news/view/31599/Massive-Dark-Web-Bust-Seizes-6.5-Million-From-179-Drug-Dealers.html" t "5064576942ac01e4fa35e726a1c88d81ba1b2397")
 ("https://packetstormsecurity.com/news/view/31598/Healthcare-Lags-Behind-In-Critical-Vulnerability-Management.html" t "7de2df63fa6b5475c29cf9b31c3b917f0cd0c644")
 ("https://packetstormsecurity.com/files/159294/APPLE-SA-2020-09-24-1.txt" t "d049f9793e724d9df52a5843ee4dbf5da0b85010")
 ("https://packetstormsecurity.com/files/159293/USN-4540-1.txt" t "998be49ad8f2e3ab1f904b26f74f6b967d5344f5")
 ("https://packetstormsecurity.com/files/159292/bigtreecms4410-exec.txt" t "4bdcec0587ac0838c9577df0506b99eabbc5f5e4")
 ("https://packetstormsecurity.com/files/159291/anchorcms0127-xss.txt" t "3487f56976379ccd7a73c360584409bf873ed3de")
 ("https://packetstormsecurity.com/files/159290/USN-4539-1.txt" t "43c9de4dceb1b66932057ffb0cbf21cbfa34daeb")
 ("https://packetstormsecurity.com/files/159289/wireshark-3.2.7.tar.xz" t "dcc0f74838385fca2d1936321e8c1a270ab43858")
 ("https://packetstormsecurity.com/files/159288/falco-0.26.0.tar.gz" t "94f93780b66d000bb5fccf33c1b0d250daf4c642")
 ("https://packetstormsecurity.com/files/159287/simpleonlinefood10-sql.txt" t "88081df2fbc1ef616a948fd61e4ed828ba2dd813")
 ("https://packetstormsecurity.com/files/159285/USN-4536-1.txt" t "cee459bbba51c2d3c1799b689aa4ef70328dc0f7")
 ("https://packetstormsecurity.com/files/159284/USN-4538-1.txt" t "ba5636a6c5da7f7ef4b5f483091a0b3dfdb5fc41")
 ("https://packetstormsecurity.com/files/159283/USN-4537-1.txt" t "870c18580402916fab3a34b0ac5d2e096017c6c0")
 ("https://packetstormsecurity.com/files/159282/RHSA-2020-3835-01.txt" t "14c2dd45bce3734725b3b4166207133f4f77a2a1")
 ("https://packetstormsecurity.com/files/159281/RHSA-2020-3832-01.txt" t "f560732cda8aab26f21e1daf561a8f30d5cdba67")
 ("https://packetstormsecurity.com/files/159280/RHSA-2020-3836-01.txt" t "9002dafd5c375d9e12dbc44039da9de9c80a787e")
 ("https://packetstormsecurity.com/files/159279/RHSA-2020-3833-01.txt" t "05576a5b428751c754ff5306291408774b780bef")
 ("https://packetstormsecurity.com/files/159278/RHSA-2020-3834-01.txt" t "8ce2cfac5a19a0882553e20f321387d4cf359b8a")
 ("https://packetstormsecurity.com/files/159277/USN-4535-1.txt" t "0ed0710b58ee99dded18c258909ad4e4a5ab35d8")
 ("https://packetstormsecurity.com/files/159276/RHSA-2020-3806-01.txt" t "0afa3682c592fd5e57e2ea327dfb108872edb392")
 ("https://packetstormsecurity.com/files/159275/RHSA-2020-3807-01.txt" t "5e69991ed1eaef6f73321d2bffb8f96b19ea0653")
 ("https://packetstormsecurity.com/files/159286/ios-swift-jailbreak.pdf" t "3f2785b24e6041f9a1b5970eeab8aba210a278c9")
 ("https://packetstormsecurity.com/files/159274/USN-4534-1.txt" t "b5a792a5b161f6d6afe81991f5d49f7e4c07079d")
 ("https://packetstormsecurity.com/files/159273/RHSA-2020-3809-01.txt" t "9c7abbf219f10905d7e2250631f64d296153fd38")
 ("https://packetstormsecurity.com/files/159272/RHSA-2020-3808-01.txt" t "e7ce2f0d5c4d3994e99a3e8fb99626381da7afd2")
 ("https://packetstormsecurity.com/files/159271/RHSA-2020-3817-01.txt" t "38ccee5dad8dc1773a6dbb25452189d0ba687552")
 ("https://packetstormsecurity.com/files/159270/USN-4533-1.txt" t "a5f488cf2ae839bd0cae8ba6fd6c73410405ef03"))
  :END:

*** iOS Swift Anti-Jailbreak Bypass With Frida
    [2020-09-23 Wed 17:22]
    Whitepaper called iOS Swift Anti-Jailbreak Bypass with Frida.
    [[https://packetstormsecurity.com/files/159286/ios-swift-jailbreak.pdf]]


*** Red Hat Security Advisory 2020-3807-01
    [2020-09-24 Thu 00:30]
    Red Hat Security Advisory 2020-3807-01 - The org.ovirt.engine-root is a core component of oVirt. Issues addressed include code execution and cross site scripting vulnerabilities.
    [[https://packetstormsecurity.com/files/159275/RHSA-2020-3807-01.txt]]


*** Red Hat Security Advisory 2020-3806-01
    [2020-09-24 Thu 00:30]
    Red Hat Security Advisory 2020-3806-01 - Red Hat support for Spring Boot provides an application platform that reduces the complexity of developing and operating applications for OpenShift as a containerized platform. This release of Red Hat support for Spring Boot 2.2.6.SP2 serves as a replacement for Red Hat support for Spring Boot 2.2.6.SP1, and includes security and bug fixes and enhancements. For further information, refer to the release notes linked to in the References section. Issues addressed include cross site scripting and denial of service vulnerabilities.
    [[https://packetstormsecurity.com/files/159276/RHSA-2020-3806-01.txt]]


*** Ubuntu Security Notice USN-4535-1
    [2020-09-24 Thu 00:30]
    Ubuntu Security Notice 4535-1 - Gabriel Corona discovered that RDFLib did not properly load modules on the command-line. An attacker could possibly use this issue to cause RDFLib to execute arbitrary code.
    [[https://packetstormsecurity.com/files/159277/USN-4535-1.txt]]


*** Red Hat Security Advisory 2020-3834-01
    [2020-09-24 Thu 19:34]
    Red Hat Security Advisory 2020-3834-01 - Mozilla Firefox is an open-source web browser, designed for standards compliance, performance, and portability. This update upgrades Firefox to version 78.3.0 ESR. Issues addressed include cross site scripting, spoofing, and use-after-free vulnerabilities.
    [[https://packetstormsecurity.com/files/159278/RHSA-2020-3834-01.txt]]


*** Red Hat Security Advisory 2020-3833-01
    [2020-09-24 Thu 19:34]
    Red Hat Security Advisory 2020-3833-01 - Mozilla Firefox is an open-source web browser, designed for standards compliance, performance, and portability. This update upgrades Firefox to version 78.3.0 ESR. Issues addressed include cross site scripting, spoofing, and use-after-free vulnerabilities.
    [[https://packetstormsecurity.com/files/159279/RHSA-2020-3833-01.txt]]


*** Red Hat Security Advisory 2020-3836-01
    [2020-09-24 Thu 19:34]
    Red Hat Security Advisory 2020-3836-01 - The kernel packages contain the Linux kernel, the core of any Linux operating system. Issues addressed include a null pointer vulnerability.
    [[https://packetstormsecurity.com/files/159280/RHSA-2020-3836-01.txt]]


*** Red Hat Security Advisory 2020-3832-01
    [2020-09-24 Thu 19:34]
    Red Hat Security Advisory 2020-3832-01 - Mozilla Firefox is an open-source web browser, designed for standards compliance, performance, and portability. This update upgrades Firefox to version 78.3.0 ESR. Issues addressed include cross site scripting, spoofing, and use-after-free vulnerabilities.
    [[https://packetstormsecurity.com/files/159281/RHSA-2020-3832-01.txt]]


*** Red Hat Security Advisory 2020-3835-01
    [2020-09-24 Thu 19:35]
    Red Hat Security Advisory 2020-3835-01 - Mozilla Firefox is an open-source web browser, designed for standards compliance, performance, and portability. This update upgrades Firefox to version 78.3.0 ESR. Issues addressed include cross site scripting, spoofing, and use-after-free vulnerabilities.
    [[https://packetstormsecurity.com/files/159282/RHSA-2020-3835-01.txt]]


*** Ubuntu Security Notice USN-4537-1
    [2020-09-24 Thu 19:35]
    Ubuntu Security Notice 4537-1 - Vaisha Bernard discovered that Aptdaemon incorrectly handled the Locale property. A local attacker could use this issue to test for the presence of local files.
    [[https://packetstormsecurity.com/files/159283/USN-4537-1.txt]]


*** Ubuntu Security Notice USN-4538-1
    [2020-09-24 Thu 19:35]
    Ubuntu Security Notice 4538-1 - Vaisha Bernard discovered that PackageKit incorrectly handled certain methods. A local attacker could use this issue to learn the MIME type of any file on the system. Sami Niemimäki discovered that PackageKit incorrectly handled local deb packages. A local user could possibly use this issue to install untrusted packages, contrary to expectations.
    [[https://packetstormsecurity.com/files/159284/USN-4538-1.txt]]


*** Ubuntu Security Notice USN-4536-1
    [2020-09-24 Thu 19:35]
    Ubuntu Security Notice 4536-1 - Youssouf Boulouiz discovered that SPIP incorrectly handled login error messages. A remote attacker could potentially exploit this to conduct cross-site scripting attacks. Gilles Vincent discovered that SPIP incorrectly handled password reset requests. A remote attacker could possibly use this issue to cause SPIP to enumerate registered users. Guillaume Fahrner discovered that SPIP did not properly sanitize input. A remote authenticated attacker could possibly use this issue to execute arbitrary code on the host server. Various other issues were also addressed.
    [[https://packetstormsecurity.com/files/159285/USN-4536-1.txt]]


*** Simple Online Food Ordering System 1.0 SQL Injection
    [2020-09-24 Thu 19:37]
    Simple Online Food Ordering System version 1.0 suffers from a remote SQL injection vulnerability.
    [[https://packetstormsecurity.com/files/159287/simpleonlinefood10-sql.txt]]


*** Falco 0.26.0
    [2020-09-24 Thu 19:50]
    Sysdig Falco is a behavioral activity monitoring agent that is open source and comes with native support for containers. Falco lets you define highly granular rules to check for activities involving file and network activity, process execution, IPC, and much more, using a flexible syntax. Falco will notify you when these rules are violated. You can think about falco as a mix between snort, ossec and strace.
    [[https://packetstormsecurity.com/files/159288/falco-0.26.0.tar.gz]]


*** Wireshark Analyzer 3.2.7
    [2020-09-24 Thu 19:52]
    Wireshark is a GTK+-based network protocol analyzer that lets you capture and interactively browse the contents of network frames. The goal of the project is to create a commercial-quality analyzer for Unix and Win32 and to give Wireshark features that are missing from closed-source sniffers. This is the source code release.
    [[https://packetstormsecurity.com/files/159289/wireshark-3.2.7.tar.xz]]


*** Ubuntu Security Notice USN-4539-1
    [2020-09-24 Thu 19:54]
    Ubuntu Security Notice 4539-1 - Andrew Bartlett discovered that DAViCal Andrew's Web Libraries did not properly manage session keys. An attacker could possibly use this issue to impersonate a session.
    [[https://packetstormsecurity.com/files/159290/USN-4539-1.txt]]


*** Amazon Unveils Flying Ring Security Drone
    [2020-09-24 Thu 19:48]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31607/Amazon-Unveils-Flying-Ring-Security-Drone.html]]


*** Twitter Prepares For US Elections With Security Training, Pen Tests
    [2020-09-24 Thu 19:48]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31605/Twitter-Prepares-For-US-Elections-With-Security-Training-Pen-Tests.html]]


*** Facebook Shuts Down Russians Posting As Journalists
    [2020-09-24 Thu 19:48]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31606/Facebook-Shuts-Down-Russians-Posting-As-Journalists.html]]


*** Microsoft Leaks 6.5TB In Bing Search Data Via Unsecured Elastic Server
    [2020-09-24 Thu 19:48]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31604/Microsoft-Leaks-6.5TB-In-Bing-Search-Data-Via-Unsecured-Elastic-Server.html]]


*** Anchor CMS 0.12.7 Cross Site Scripting
    [2020-09-25 Fri 15:50]
    Anchor CMS version 0.12.7 suffers from a persistent cross site scripting vulnerability.
    [[https://packetstormsecurity.com/files/159291/anchorcms0127-xss.txt]]


*** BigTree CMS 4.4.10 Remote Code Execution
    [2020-09-25 Fri 15:51]
    BigTree CMS version 4.4.10 suffers from a remote code execution vulnerability.
    [[https://packetstormsecurity.com/files/159292/bigtreecms4410-exec.txt]]


*** Ubuntu Security Notice USN-4540-1
    [2020-09-25 Fri 15:53]
    Ubuntu Security Notice 4540-1 - Denis Andzakovic discovered that atftpd incorrectly handled certain malformed packets. A remote attacker could send a specially crafted packet to cause atftpd to crash, resulting in a denial of service. Denis Andzakovic discovered that atftpd did not properly lock the thread list mutex. An attacker could send a large number of tftpd packets simultaneously when running atftpd in daemon mode to cause atftpd to crash, resulting in a denial of service. Various other issues were also addressed.
    [[https://packetstormsecurity.com/files/159293/USN-4540-1.txt]]


*** Apple Security Advisory 2020-09-24-1
    [2020-09-25 Fri 15:53]
    Apple Security Advisory 2020-09-24-1 - macOS Catalina 10.15.6 Supplemental Update, Security Update 2020-005 High Sierra, Security Update 2020-005 Mojave are now available and address code execution and out of bounds read vulnerabilities.
    [[https://packetstormsecurity.com/files/159294/APPLE-SA-2020-09-24-1.txt]]


*** Alien Android Banking Trojan Sidesteps 2FA
    [2020-09-25 Fri 15:49]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31611/Alien-Android-Banking-Trojan-Sidesteps-2FA.html]]


*** Cambridge Analytica's Ex-CEO Banned From Running Companies
    [2020-09-25 Fri 15:49]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31610/Cambridge-Analyticas-Ex-CEO-Banned-From-Running-Companies.html]]


*** Update Now: Cisco Warns Over 25 High Impact Flaws
    [2020-09-25 Fri 15:49]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31608/Update-Now-Cisco-Warns-Over-25-High-Impact-Flaws.html]]


*** Instagram Flaw Shows Importance Of Managing Third-Party Apps, Images
    [2020-09-25 Fri 15:49]
    <![CDATA[]]>
    [[https://packetstormsecurity.com/news/view/31609/Instagram-Flaw-Shows-Importance-Of-Managing-Third-Party-Apps-Images.html]]

** ZDNet Entries
  :FEEDSTATUS:
(("c96879f5-54bc-42cd-8259-c0cc8182a4d6" t "43e7c96182a0cc5a687c888452ddf2556637fdfc")
 ("bcf83b62-3d0f-43d1-a781-4384e41063f9" t "dfb9f92a452598fbb36999edbeb742bc39125e1a")
 ("6ff98e67-4861-4f14-bc6f-1c6f60a119a9" t "39b5d1b84bd7a92b4e63181736176d8e47e9a1e6")
 ("71ae0bb5-dbe8-429a-9062-06f75137aa2e" t "d15ba12de3cf47de256ad6b01bccfb3430ca3587")
 ("d0fc83c7-deb8-4d8f-b907-eda5ebc7e54b" t "0a4b94106571f93bc707616bea275a80e46e6fee")
 ("4f67002a-973d-4106-a9e5-4a4f2b2efee2" t "5c03eaac9de79292a04951cd9031afa32d5f63fe")
 ("d9604f9c-5bff-40a2-a1c1-3bf5f20312f2" t "0b1a5494a42c158e34ad033f0309bcfa83ee9b3d")
 ("772d2dd8-48f4-430d-a63a-bfb9d083b428" t "e9f3f4fbed3fe9f0c068900ba339af40672f25be")
 ("2a954676-f9a7-4fff-8cec-79ed69b76ca8" t "bfc50723c07d63f1a5066523a1681d8bc42c8e05")
 ("8b873a6d-931a-4c10-afda-3a94132b9d73" t "629309f8c40f3c73eedcc6cc71a451f1ccb196af")
 ("add89d96-2703-490d-8a73-b1a22c076728" t "78b82e54b030f7e164e85d7b7125f94ca6f4c760")
 ("4e253e92-b90b-44da-bcec-d15416b9ecc4" t "ffc23a09f644e10855de44ffed59c960a61bf00a")
 ("e87d095d-9df6-47ac-ad4d-f305bced62e2" t "920bb3a18bea0b6fa475ea323db7b7b656ca41c6")
 ("e7fcf1eb-e98b-42e8-a766-205284558b26" t "4c24bdbfa5ff8023ab94a5e4724dc958e4aaaccc")
 ("4abb412b-c328-4ae2-ac2b-74da6fe82296" t "1efed1ea140aaf0e806451d3de3b59bb99590a6a")
 ("e2098c02-7255-4b27-804d-88a43d0fd2b4" t "17a427285504a66f5d96fccbeb890526413acfff")
 ("3d4d843d-cda5-40e4-b7c6-b72271327018" t "e328c37519c6fbcd53d643b7fd27ad0ae43274d2")
 ("63f73cd7-a3be-42cb-bdb5-56ffba9310fe" t "d01500db243ddfea9309f98529fcfa2bf53276b7")
 ("d92f02c0-c7e0-4d6c-acb8-cb3af88f5019" t "f8964febcb70b26d8c3288c6bf1120c840babc92")
 ("ab7fa5fc-0d33-4740-93c8-e0e818b14144" t "ec77c2f9e2aead9aeedcf08e5fdb17089def3990"))
  :END:

*** ANAO finds Services Australia lacking in cyber and cost aspects of WPIT
    [2020-09-25 Fri 06:09]
    Audit Office finds at the end of WPIT, there is a chance that the whole reason for the program, to decommission ISIS, may not occur.
    [[https://www.zdnet.com/article/anao-finds-services-australia-lacking-in-cyber-and-cost-aspects-of-wpit/#ftag=RSSbaffb68]]


*** TikTok touts vigilance to prevent further distressing videos from appearing on its app
    [2020-09-25 Fri 06:49]
    The controversial video-sharing platform also said it would happily notify Australian authorities of any misinformation takedowns, if it knew who to go to.
    [[https://www.zdnet.com/article/tiktok-touts-vigilance-to-prevent-further-distressing-videos-from-appearing-on-its-app/#ftag=RSSbaffb68]]


*** Scouts Victoria phished for data treasure trove including TFNs and bank account history
    [2020-09-25 Fri 07:00]
    Scouts Victoria was the subject of a phishing attack that has resulted in a significant amount of highly sensitive, personally-identifying information being accessed by criminals.
    [[https://www.zdnet.com/article/scouts-victoria-phished-for-data-treasure-trove-including-tfns-and-bank-account-history/#ftag=RSSbaffb68]]


*** First hydrogen-powered aircraft takes flight in ‘major’ breakthrough for the industry
    [2020-09-25 Fri 09:36]
    ZeroAvia says this form of next-generation craft will eventually match fossil fuel counterparts.
    [[https://www.zdnet.com/article/first-hydrogen-powered-aircraft-takes-flight-in-major-breakthrough-for-the-industry/#ftag=RSSbaffb68]]


*** Motorola Moto G 5G Plus review: A great budget smartphone, with added 5G support
    [2020-09-25 Fri 10:09]
    With great battery life, a large screen, some nice personalisation features and the future-proofing of 5G support, the Moto G 5G Plus is probably the best budget handset around right now.
    [[https://www.zdnet.com/product/motorola-moto-g-5g-plus/#ftag=RSSbaffb68]]


*** COVID at work: How the virus is even changing how we gain entry to the office
    [2020-09-25 Fri 10:37]
    As organizations around the world prepare for the post-pandemic workplace, access-control issues loom large.
    [[https://www.zdnet.com/article/covid-at-work-how-the-virus-is-even-changing-how-we-gain-entry-to-the-office/#ftag=RSSbaffb68]]


*** Brazil investigates online voting
    [2020-09-25 Fri 10:55]
    A demo in the upcoming elections will inform the potential future adoption of the remote model
    [[https://www.zdnet.com/article/brazil-investigates-online-voting/#ftag=RSSbaffb68]]


*** Airbnb may be exposing private host inbox messages, bookings and earnings data
    [2020-09-25 Fri 10:56]
    Airbnb hosts report that they are able to access inboxes that do not belong to them.
    [[https://www.zdnet.com/article/airbnb-security-incident-may-be-leaking-host-inbox-messages-bookings-information/#ftag=RSSbaffb68]]


*** Accenture's Kathryn Ross on cultivating VC funding for Black entrepreneurs
    [2020-09-25 Fri 11:00]
    Accenture's Black Founders Development Program includes strategic investment in North America and expansion globally as well as community engagement and thought leadership.
    [[https://www.zdnet.com/article/accentures-kathryn-ross-on-cultivating-vc-funding-for-black-entrepreneurs/#ftag=RSSbaffb68]]


*** Follow-the-leader: A shortcut to autonomous trucking
    [2020-09-25 Fri 11:00]
    Auto trucks don't need drivers if they have a good guide.
    [[https://www.zdnet.com/article/follow-the-leader-a-shortcut-to-autonomous-trucking/#ftag=RSSbaffb68]]


*** Windows XP source code leaked online, on 4chan, out of all places
    [2020-09-25 Fri 11:02]
    Source code for several operating systems, including Windows XP and Windows Server 2003, leaked in 42.9 torrent file.
    [[https://www.zdnet.com/article/windows-xp-source-code-leaked-online-on-4chan-out-of-all-places/#ftag=RSSbaffb68]]


*** Verizon, AT&T settle overcharging whistleblower case for $116 million
    [2020-09-25 Fri 11:39]
    Updated: The lawsuit alleged that both telecoms giants overcharged government agencies for over a decade.
    [[https://www.zdnet.com/article/verizon-at-t-settle-overcharging-whistleblower-case-for-116-million/#ftag=RSSbaffb68]]


*** Update now: Cisco warns over 25 high-impact flaws in its IOS and IOS XE software
    [2020-09-25 Fri 11:52]
    Cisco urges customers using IOS and IOS XE devices and software to apply updates for dozens of high-severity vulnerabilities.
    [[https://www.zdnet.com/article/update-now-cisco-warns-over-25-high-impact-flaws-in-its-ios-and-ios-xe-software/#ftag=RSSbaffb68]]


*** A closer look at Microsoft Azure Arc
    [2020-09-25 Fri 12:00]
    The promise of Azure Arc is providing the simplicity of the cloud control plane inside the data center. A year after announcement with the core platform now going GA, we thought it would be a good time for a deeper dive to see how Azure Arc actually works.
    [[https://www.zdnet.com/article/a-closer-look-at-microsoft-azure-arc/#ftag=RSSbaffb68]]


*** Preparing for the future: The 2020s will demand more from your tech
    [2020-09-25 Fri 12:00]
    What worked in the 2010s will not work in the 2020s as we see business shift from global toward hyperlocal operations. Aligning your tech stack to address the highest risks to your organization and pursue the right innovations will be the differentiator for future-fit firms in the 2020s.
    [[https://www.zdnet.com/article/preparing-for-the-future-the-2020s-will-demand-more-from-your-tech/#ftag=RSSbaffb68]]


*** Always Home Cam: Amazon's robot drone flying inside our homes seems like a bad idea
    [2020-09-25 Fri 12:02]
    Amazon doesn't just want to hear you at home. It wants to be a full-fledged housemate. But much as an indoor flying drone scares me, I think I have to have one.
    [[https://www.zdnet.com/article/always-home-cam-amazons-robot-drone-flying-inside-our-homes-seems-like-a-bad-idea/#ftag=RSSbaffb68]]


*** Tech jobs: Outlook for hiring is still uncertain
    [2020-09-25 Fri 12:15]
    New job listings for developers fell between the first and second quarter of 2020, except in two major tech cities.
    [[https://www.zdnet.com/article/tech-jobs-outlook-for-hiring-is-still-uncertain/#ftag=RSSbaffb68]]


*** Of course I want an Amazon drone flying inside my house. Don't you?
    [2020-09-25 Fri 12:26]
    Amazon's riveting new product, the Ring Always Home Cam, is truly sent from the gods.
    [[https://www.zdnet.com/article/of-course-i-want-an-amazon-drone-flying-inside-my-house-dont-you/#ftag=RSSbaffb68]]


*** Python programming language: Here's what's new in version 3.9 RC2
    [2020-09-25 Fri 12:29]
    Python 3.8 will retain a few Python 2.7 compatibility layers to support projects that rely on 2.7.
    [[https://www.zdnet.com/article/python-programming-language-heres-whats-new-in-version-3-9-rc2/#ftag=RSSbaffb68]]


*** Microsoft Ignite 2020: All the news from this week's Redmond's IT Pro conference
    [2020-09-25 Fri 13:00]
    From Project Cortex and Azure resiliency to Teams and Edge on Linux, here's everything you need to know about the news out of Microsoft's Ignite conference.
    [[https://www.zdnet.com/article/microsoft-ignite-2020/#ftag=RSSbaffb68]]


*** Amazfit PowerBuds review: Heart rate sensor, innovative ear hooks, and long battery life
    [2020-09-25 Fri 15:25]
    Bluetooth wireless headsets have become a standard today and Amazfit just confirmed you don't have to spend more than $99 for an outstanding option. If you exercise with music then you will appreciate the design elements of the PowerBuds.
    [[https://www.zdnet.com/product/amazfit-powerbuds/#ftag=RSSbaffb68]]

** Stallman Entries
  :FEEDSTATUS:
(("a27d932d7c947097b379e969fff74237" t "9840675cccd34250a838453f35360006991cb1f4")
 ("93ad17a9de045cf078a28498c154c0b3" t "a15877f59e8dc5f470b6fbea0dba76dd01ec1be9")
 ("46a6e6d2b323499f10aa1b17eb068f1b" t "0c25e27cb81619fae0aec6cc790a4848f264442b")
 ("911f9806a4390be5c7506b9ff5001812" t "9d757b5b2723ae0b2fe8e85259903252b00f2f76")
 ("68121e8d88f2721d516104b707496e5c" t "47d0f0364c7f2d0d1469330fd4c2c24dec78c7e9")
 ("4de44921f3764b5be8e5e6d741031d10" t "54c74bf9bfdbaf83ec0dd914d415006e3a0e0cdf")
 ("91f68a01aed2c980ab528d0c5e062c4e" t "744ded34e8e5d60ec96a690e9394634ea0c4d5dc")
 ("a00b036d272d569496bb5548a98f780b" t "6c554c581cba3832fc2e55413b53685a80315974")
 ("1ed8ede80f090f99c472cddfd2c5bac0" t "b03f48ff61ab16ef1a4e6ecc9f1b0d6290772508")
 ("4abc13789f92ba360e8f113faec02e42" t "e8bab1799364ac766b5f0ea1cf0b6ece5f0b6c0a")
 ("3cd251ec785362b641d35038f33b9c29" t "cc455aa9268c8cee2c24ef1cdbc36fb9b311fabd")
 ("d567f5243b4e965a78ba9e52f11cc5e1" t "89f1a3316f0ce7692468846a1d849b246a205ecd")
 ("725d46b8525670d22e79ce99a21696d8" t "65a85430baab35fbed8b7f62a61bd8e38f813f7a")
 ("6deea5740fdb0bbf6141042bf7d7a7ae" t "07125b0e7c2ee14c2b6d7be52b5f01ee671dae5f")
 ("43eada900ea424919e3cb2e5cb7c9db4" t "6ac67e37a2f92c8db7afaa500cea38c295f20b74")
 ("ba6fb585f0a7647a534ef0b9a16a2916" t "632f257af84cd67f3fa5827ef31c9eef57220abe")
 ("c511d03f05c378c4b4fd754942156586" t "38de893a483a4df2230b83d6369f4dc0894ed881")
 ("377d058ca5205ed3329af26583cb3aa5" t "4bc7793ba8ddcba8a6434d0c0898383198848de8")
 ("d25bea703c0ffbd6c2f244c2e2c99d7b" t "0ecd8c9cb2df47dae7c325d8f9ef3b4442a955fd")
 ("6207678ae7cc0617f0c1483ed067a10a" t "263edd664c1877203b840ef86a8c0b50db2d367a")
 ("0056439af5ffe27853c08191ade5e284" t "b9702d402a39b35444cf75859f92025fbd4c2732")
 ("268d31ff1bca9a516be69f2e324e9004" t "a761d60e0df445204d14fd64d938b4a3bb35e8ba")
 ("3632289018255ece6cfb724b1284eb13" t "16901730bb4c75aec23111be3c67870103ccd220")
 ("0d71bac1ba4cf7214efffb56d341c21c" t "813d8865f23e53ff8b86c2c9ba070eac35d7d902")
 ("37321ca34e9f2026d749e034bbf54398" t "cb21714813bf730b852cf5b7a75517bf9e528746")
 ("a117fd0f83634992e9dd295c8e5d1de6" t "80ce03381136b9e09f1951967f97b8c0f196426e")
 ("85509f383eef42441c489942b951f1bb" t "35cd0bfaf44ab9548ee288dacaa917275a780286")
 ("d5bee5c73d1377eb5d979c157ecfe985" t "5746f0f8df723253a5bc4d0e37d52277cb5b140b")
 ("48f5fbcabf37971ea745bf948757950f" t "cd3e1f494ea62173c8aef3c64816a618e12e3c04")
 ("c11b0960b932bf093976f557de587229" t "b9488e214070d9852ac4cd9f5b11bd1564d76644")
 ("d3b2a310ed0cf47126b1f92e89754794" t "0c0fa50e5004cd607558b07ff13d8fc2fb416373")
 ("89d82500b8a0d2e7b3474153a99d9c64" t "a6deab7dcf2b187fd2759075b3fa1d9383e67213")
 ("9dfa399ebc218712d2f026bfd0ba24bd" t "8c6d3f1431a44c31b727aa3b5755dee802dc76e1")
 ("2803dd149fefe9bbe235c7367a37a5d6" t "52607c60c31266a16c0dc94f635bd3bf1350de79")
 ("3d1b8259fa27dda76982ff0dbbc4da4f" t "9045d435340173fda5440f4421b9284ae73dbff0")
 ("aae8dabcfc2c457bfc738803a83a7fa4" t "603c45ca00b84ea096239ed9f0edfecd7726208b")
 ("65e2e998c4fa649857d7c92ac624de16" t "485633e8252141bb39be86848faa0e73355f8489")
 ("abd9d4c936fbac20202ae69ed26e69bd" t "3fd67bf556fe0430a18c1ec423feda7e556ec4a7")
 ("f8ee1f9673d471116820c42262788d21" t "59c9e3e9cee966321f656df6244c9b861d4e6a63")
 ("9826f882fca000e5e142fe6a0972a141" t "d498d0d7de10ca4d87f48b0f3a35d1ff4073ba0d")
 ("e2f2ef34ba5fa607abb0e075fbf0140e" t "5a2deef39881e4f4a663a78ad52e298e35ee18ba")
 ("44255f17f1948b8fc07ecf37067bd4f9" t "c618552fc26dbd0adc4cfd5c283b6fb31c47b78f")
 ("5f244563e56012d9259036c8c1dc900a" t "03280419f48b92a758f7a4e7a19465174fffe6d6")
 ("85c42ec870c72fd727814691ea291906" t "b67b57b993360c5da8b846699e223e03b14a55ed")
 ("bf99e3035f3cc863568c14004664ccfc" t "3e9ab2d0389f76cb1b9895a588ea8a67b2adf503")
 ("378e545dee27ba9b707c234f57af8587" t "17592545ede4a7b6649c07ab063c598b432e99ea")
 ("f4098693b5d6912543b47d4f3b8cd91f" t "66f754a548c78ae77f87ee8ee9a2b459056fc18c")
 ("6d0f2f3f6fff5d4b480505fc7b136ded" t "400096406984fae8a234a9d7c0db38ebcc445a36")
 ("b3037c9afea4f32947b7fbece424ba76" t "6732ed32f00e5d22b6bb877a925fea01d9a1d0fc")
 ("39bd39d589867bdb491e0af706c6835c" t "9bbbb671e24e6ee7222b1779b52db0877ece5b74")
 ("39c2bde1e52ac394535c71d60f9bd98e" t "ad445d143b88a61031e8a227e187b21bcb4a5ab4")
 ("9cb9f54b0cb2ac7f9977cc51b750641e" t "18138ae2a86029db24714450456d06e15acdaaaa")
 ("936b78b050638acb895f3c539343f598" t "68fa201742081b64b2690acc78d5d31ff9032435")
 ("4059b7c0aa7588f74b869ba8a108245c" t "643bcafa1e6f923f2aaa996389c8070e3fb7b1ab")
 ("9325891a2c321d839af66c35c0b5ad0c" t "d6b30d78c52fafa0dfde3fe8e030c185b7b8219b")
 ("2bcf47a0386abd1b7a46b2b6e3dd3287" t "4cdb24462f5230d08c2d1f13db4c6371c1b58e1b")
 ("fbf6f3b8ecb1436ceb8bd7dcb8ebaf6d" t "5bafa1c6afd96c758d4ca1f52b28ad4953cd8b3e")
 ("410ecc4136e279264335e6308e8568f2" t "e3263f9246f1d1250a0278fb2af5250a3e98dae7")
 ("46deb9d74256d8068d51913ff479593b" t "824ea796f0bb3e23a998b3d31e1527a9cba5ad1a")
 ("fe01afe349761be34a8976e0cb1645f4" t "442b315f7fef9bae1ad7ada6449221310c8d194e")
 ("4d4151c263957338698e510b5a138f3d" t "2845a03915cf326522e196fbd53c405f4d0faaa0")
 ("600186381d137b5e00f9eb6737e76698" t "894d1ccc05fde3341de3f2ea369529d0a5854c5e")
 ("49d46e982a76e22b3ff7c718e6b61693" t "a3f605f1416b17bec741dad0d50f76d580287b6e")
 ("e4f54c340fb453a3d8edde9be66ddcf5" t "e0dbf68b90cd804f12daaac0b8020629e4e44424")
 ("dfce2f4d37dad342b50e1b5f863c2239" t "4218d3aa10f679cd0b469491b72657333ed9300b")
 ("6e57c7c26484e03450940990a1184448" t "289ed3ec3f04cb5efa6e4ce54b7dcabbfb12e672")
 ("8b05d0001073b47451a54617af50ee6e" t "7f5a20b8db98fe7f87446ee7359febb2c613f3c4")
 ("7e22721dc7c93fdfd61c15876bec3ef9" t "a1975c69851310ded936114a796db14ef080bc68")
 ("3687398aea416c5f64fa7f2916a00331" t "8be920e9fe61e7a756906a15f20a2074cd1317e1")
 ("ec2518a44f211c24cf7df86eaf610c48" t "522d9370e8435a059d4aa7c08a34473aa1be173c")
 ("916943fabdd2320b641ac54c85a68bfc" t "40bea4a408626043a989f14b76a0e6963f45c5a9")
 ("d7ede471675f7698fd5f24f766e54f71" t "b659cd343ba2cc8af25e5ee62fa0b2adfb8e4ba3")
 ("151f329416fc5b40b521c2e641c3c063" t "8cc949907a80e6633113f49a7af53ccb0541ac44")
 ("ce5d02bd14cec0065eb40826a2f6c422" t "000d4a7fbb6afa1de1d1b05bf04b112d91530c26")
 ("58c067c573bd1ef6397f6216c8793ad4" t "1b2f85b6cd8210824271bda2cfa03ef070788785")
 ("0edafee25caac0fd3ff3e9dc410a4de7" t "3ba7d796747059393b1d69ca814c8fe3c5bad1f3")
 ("951b43a5e8351d105c1148be6aaf0bfc" t "396a0970739d77451f959882ccc7f9a782edf18c")
 ("480504f80107b573c907dc202c950647" t "4b7fbea0d5b298348fdfd02afdb08adca295d332")
 ("3f41f11e4b204ba73106938b9309d9f9" t "f75acf596e13bfe67be51c15c847ff850c7c8b84")
 ("912b487fb13f976aa04b7260fcb11b72" t "e42d0d1927f00d35292bcb479c2e6f192709a8d7")
 ("85631f805d22f011a437d6776bc07266" t "0cfc01f5b1e177c8647f3998895efa0a56222ccf")
 ("7101ea59f1a648013fca66092cf18b5e" t "abd9072dac2c9aef3c2e45676213345e80df9753")
 ("8adf035e922ce5c95ed67bd6c7eeafe9" t "6bbc7ddab0ff81de34f68b5f776768b421d08cea")
 ("edf98365efc069731bfd0620c02acbba" t "ad167041a7346a8598bef8e846fe78d103e4137b")
 ("2224fc0329eaeedb224f71501106d11e" t "97d7a9fa3bf2b09e6367eeb27b3358946e58e488")
 ("698af56abfba254153c8de241f2c9715" t "3e788cfb640b0c79fc51f0b3dadf07d014779f6e")
 ("7b8e37bfaaca7a07ba803fcbd8c3cfb1" t "7aea64e3efb4190885e6c1b9c90caab2c9667cec")
 ("e98153a85e24f7b2dba164004a17472f" t "c56788883d4ca016562e505f7433788e3f203a89")
 ("6e60ce29c4bdf698ea6ee0dc23df487e" t "e217c5dac111e51bf1b95e97a502f65235e19a54")
 ("b5c0452b825e5a60972077811992ebf0" t "ef65416a28f8917bd53fd08aa64a60ffc77b63ba")
 ("106f4a23effe100be0b90870223c8607" t "e6af754513c8572779b640dbc8b393bdbfe10039")
 ("8a82f16d1e05344fc15eea2c013b0aea" t "d9f6ec4ad06efcceb4fb23e450b3f328b166e1a5")
 ("31915067c8cdace363b4d819f86f616a" t "79b9005b94848fd297c351a6de4a9a77ef230ff9")
 ("d9d4076b4f1eb653df7e5c1a9aaa9221" t "ae6bba654ba54ca90bbcacd9abda3ddb0e55b691")
 ("844632b04cb84d59d3452749fa67747e" t "410a72962d2878a7d97590bf71b31230b31ace88")
 ("a989f1d43afc8bdf53db16c9dbd35d1e" t "1646769031bc5623d137f2d2411ce34f6aab4151")
 ("8c1bd9481dd536c60c12ec674d0e814e" t "806951d1b4801ec3b6d734ab42591b56f5faeeee")
 ("1f1dc29963778b7ea9fff7a6c6591de0" t "6b4283cb9ad59edec589d539c2fdc334dd10f97c")
 ("d7430e57ea4824969f6b644c5b56c9b4" t "3918233856ce5bfc3f15e93a23573f975d35bf1d")
 ("f9a88f5cf747446e9a807198dbfc0f15" t "00290e93773d07e63083220b0115f96e6015f11b")
 ("ae1af3e0b434cbbbcb23ed3b0e4dbbff" t "2d8994f18ff22fcf88376f64801e00030d84af9a"))
  :END:

*** <![CDATA[Perspectives from a worried military spouse]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  *Perspectives <a href="https://www.commondreams.org/views/2020/09/22/war-zone-america">on a riven nation from a worried military spouse</a>.*




  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Perspectives_from_a_worried_military_spouse%29]]


*** <![CDATA[Stealing the election]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  *Trump Keeps Telling Us How He and Republicans Plan to Steal This Election.
   <a href="https://www.commondreams.org/views/2020/09/23/trump-keeps-telling-us-how-he-and-republicans-plan-steal-election">Can we stop him and save our republic before it's too late</a>?*

  <p>
  Is "steal" the correct word?  The final step would use a loophole in
  the Constitution,  <a href="https://www.forbes.com/sites/tommybeer/2020/09/23/report-trump-campaign-actively-discussing-radical-measures-to-bypass-election-results/#345778e04800">and that <em>a such</em> would not be stealing it</a>.
    But the first step is a fraudulent accusation of fraud, and I think that
  would justify the word "steal".

  <p>
  Why are Republicans in control of all the swing states' legislatures?
  Some of those states now vote majority Democrat, but gerrymandering
  has prevented the voters from electing legislators that reflect their
  views.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Stealing_the_election%29]]


*** <![CDATA[Zero greenhouse emissions vehicles]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  Governor Newsom ordered that all vehicles sold in California after 2035
  make zero greenhouse gas emissions, but he failed to take real steps
  <a href="https://www.commondreams.org/newswire/2020/09/23/governor-gavin-newsoms-executive-order-makes-great-strides-zero-emissions">to reduce oil and gas extraction in the state</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Zero_greenhouse_emissions_vehicles%29]]


*** <![CDATA[Inciting violence against reporters]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  The bully continually incites violence <a href="https://www.commondreams.org/news/2020/09/23/these-are-actions-fascist-press-rights-advocates-warn-dangerous-pattern-trump-again">against reporters
  but pretends not to be doing so</a>.

  <p>
  Remember how in 2016 a Republican candidate apologized for punching a
  reporter, but the <a href="https://stallman.org/glossary.html#bully">bully</a> praised it anyway?



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Inciting_violence_against_reporters%29]]


*** <![CDATA[Earth is dating the Moon]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  (<a href="https://www.theonion.com/nasa-scientists-confirm-earth-dating-the-moon-1845097495">satire</a>) *? the National Aeronautics and Space Administration
     confirmed Monday that the Earth is dating the Moon.*



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Earth_is_dating_the_Moon%29]]


*** <![CDATA[2021 Ecuador election]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  Ecuador's treacherous president Moreno is trying to rig the 2021 election
  <a href="https://www.commondreams.org/views/2020/09/23/political-trials-and-electoral-bans-battle-democracy-ecuador">by stopping Correa and his supporters from running</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%282021_Ecuador_election%29]]


*** <![CDATA[Climate activists and energy bill]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  Climate activists call <a href="https://www.commondreams.org/newswire/2020/09/23/over-100-groups-oppose-democrats-energy-bill-insufficient">for defeat of the Congressional Democrats'
  inadequate energy bill</a>.

  <p>
  The article says that passing that bill would by a "Pyrrhic" victory,
  which is incorrect use of the word.  "Pyrrhic" describes a victory won
  at such a great cost that you can't afford to win another.  (King
  Pyrrhos of Epirus said that about his victory over Rome.)  This bill
  would be, rather, a dummy victory.

  <p>
  The oil companies' conservation plans <a href="https://www.commondreams.org/newswire/2020/09/23/big-oil-reality-check-new-paper-finds-failure-across-board-oil-industry-climate">are also drastically inadequate</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Climate_activists_and_energy_bill%29]]


*** <![CDATA[Bolstering companies who laid off]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  *The Federal Reserve bond
     purchasing program meant to prevent workers from losing their jobs amid
     the Covid-19 pandemic instead bolstered companies who laid off <a href="https://www.commondreams.org/news/2020/09/23/fed-program-meant-help-workers-amid-pandemic-prioritized-wall-street-investors">more
     than one million workers while paying massive dividends to
     shareholders</a>.*



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Bolstering_companies_who_laid_off%29]]


*** <![CDATA[Hardly discussing global heating disaster]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  In this year's presidential debates, <a href="https://www.commondreams.org/views/2020/09/23/planet-stake-moderators-must-make-climate-focus-debates">the danger of global heating
  disaster may hardly be discussed</a>.

  <p>
  If there is a question about this issue, it is likely to use the
  vague, neutral term "climate change" which invites candidates to miss
  the point.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Hardly_discussing_global_heating_disaster%29]]


*** <![CDATA[Recruiting teenagers]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  In the UK, teenagers (not "children" as the article says) <a href="https://www.theguardian.com/uk-news/2020/sep/23/children-interested-in-extremism-covid-says-neil-basu-counter-terrorism-officer">are being
  recruited to violent right-wing extremism via internet communications</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Recruiting_teenagers%29]]


*** <![CDATA[Talking about concerns]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  Some large US corporations have learned to talk about concern for
  "stakeholders" other than their owners and executives, <a href="https://www.commondreams.org/news/2020/09/22/study-shows-stakeholder-capitalism-failing-live-promises-corporations-continue">but it's only
  talk</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Talking_about_concerns%29]]


*** <![CDATA[US Chamber of Commerce]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  The US Chamber of Commerce has found 23 Democrats in Congress
  sufficiently plutocratist <a href="https://theintercept.com/2020/09/24/chamber-of-commerce-democrats/">to endorse their election campaigns</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28US_Chamber_of_Commerce%29]]


*** <![CDATA[Security risk]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  *White House 'pressured official <a href="https://www.theguardian.com/books/2020/sep/24/white-house-john-bolton-book-classified-national-security-council-ellen-knight">to say John Bolton book was security risk</a>'.*

  <p>
  It's another example of how the wrecker corrupts every government activity.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Security_risk%29]]


*** <![CDATA[Manslaughter and miscarriages]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
***   Dozens of women have been convicted for manslaughter, homicide and
     aggravated homicide after having miscarriages, stillbirths and other
     obstetric emergencies since El Salvador <a href="https://www.theguardian.com/global-development/2020/sep/24/el-salvador-woman-freed-after-six-years-in-jail-following-stillbirth">introduced a total ban on
     abortion in 1998</a>.*



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Manslaughter_and_miscarriages%29]]


*** <![CDATA[Joshua tree]]>
    [2020-09-25 Fri 00:00]
    <![CDATA[<p>
  California will study whether the Joshua tree needs legal protection
  <a href="https://www.theguardian.com/us-news/2020/sep/24/california-law-two-million-year-old-joshua-tree-under-threat-climate-crisis">from being wiped out by global heating</a>.



  ]]>
    [[https://stallman.org/archives/2020-jul-oct.html#25_September_2020_%28Joshua_tree%29]]


*** You can bypass TikTok's MFA by logging in via a browser
    [2020-09-25 Fri 16:23]
    Enabling MFA in the TikTok mobile app doesn't apply it for the web dashboard. TikTok promised to fix the issue.
    [[https://www.zdnet.com/article/you-can-bypass-tiktoks-mfa-by-logging-in-via-a-browser/#ftag=RSSbaffb68]]


*** Twitter warns of possible API keys leak
    [2020-09-25 Fri 17:10]
    Incorrect server settings on the Twitter Developer portal led to browsers caching API keys, account access token and secret.
    [[https://www.zdnet.com/article/twitter-warns-of-possible-api-keys-leak/#ftag=RSSbaffb68]]


*** NumPy’s contribution to Python is remarkable, but where it goes next could be even more so
    [2020-09-25 Fri 17:19]
    NumPy, the Python package for scientific computing, is an adolescent with prospects for a prolific maturity.
    [[https://www.zdnet.com/article/numpys-contribution-to-python-is-remarkable-but-where-it-goes-next-could-be-even-more-so/#ftag=RSSbaffb68]]


*** Best mouse in 2020: From SteelSeries to Logitech, the top mice compared
    [2020-09-25 Fri 20:36]
    Finding yourself spending more and more time working from your home office? Time to kit it out with quality mice so you can get more work done in less time, and also keep your hands and wrists healthy.
    [[https://www.zdnet.com/article/best-mouse-mice-bluetooth-corded-computer/#ftag=RSSbaffb68]]

** Slashdot Entries
  :FEEDSTATUS:
((nil t "bd0be64bab5f89dc98ce06f2e19eccc8d53f59c3")
 (nil t "5fe929ea57e441bd70b63a24f6507977e46b6346")
 (nil t "52554c0752a16a94a4315606539410617a3370ab")
 (nil t "777820214f94a4903ca7e2b9d9aa720b85624baf")
 (nil t "a5c916053d2d3d06e8434dc6b9d81e8be028f69d")
 (nil t "f52e72f34bdef477a95b38121fe596b13c6e9441")
 (nil t "2a9fa97067ff15299de123b1f8b6662981ee680b")
 (nil t "cd4aef79eef8ad40f3acf641222344898c6cce36")
 (nil t "1c9bd2fb23002996c6833734bc93a6be3e9dcae2")
 (nil t "acbd1bd0d82fe4743595b42625289a6327a2cc1c")
 (nil t "3953121a774c0674f7cfaccb83fca181f92fc8d6")
 (nil t "4cd87371e1e85e07a1005a93d232337da4c37086")
 (nil t "45d4622de80b30331f73e42a3eedc0e7af38f028")
 (nil t "1fa67c59f660f033e5143ab5aa9847892921ed51")
 (nil t "f2c70a7c6bdbfbfaf7cd73ece5b840915cf4c7a7"))
  :END:
